### ISSUE TITLE
Add steps for Contributing to the repo

### ISSUE THREAD

**Issue by the-amazing-atharva** [the-amazing-atharva/intro-website-html-css#2]
Add a bullet list with generic steps to contribute

**Comment by theavitw** [comment]
Hello I am Avit. Are you looking for this issue. I can Help you . Reply On this comment

**Comment by the-amazing-atharva** [comment]
Hey Avit,
Welcome to my repository.

Sure, go ahead and send a PR !!
Do you need any help?

**Comment by the-amazing-atharva** [comment]
I have already got a PR for this issue, but dont worry there is another issue if you like to contribute
